[tool.poetry]
name = "todo-app"
version = "0.1.0"
description = ""
authors = ["Manvi Narang <manvinarang01@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
